"""Default template definitions for spec documentation."""

from .config import TemplateConfig

# Default template content with comprehensive structure
DEFAULT_INDEX_TEMPLATE = """# {{filename}}

**Location**: `{{filepath}}`
**Type**: {{file_type}}
**Last Updated**: {{date}}

## Purpose

{{purpose}}

## Overview

{{overview}}

## Key Responsibilities

{{responsibilities}}

## Dependencies

{{dependencies}}

## API/Interface

{{api_interface}}

## Usage Examples

```{{file_extension}}
{{example_usage}}
```

## Configuration

{{configuration}}

## Error Handling

{{error_handling}}

## Testing

{{testing_notes}}

## Performance Considerations

{{performance_notes}}

## Security Considerations

{{security_notes}}

## Future Enhancements

{{future_enhancements}}

## Related Documentation

{{related_docs}}

## Notes

{{notes}}

---
*Generated by spec-cli on {{date}}*
"""

DEFAULT_HISTORY_TEMPLATE = """# History for {{filename}}

**Location**: {{filepath}}

## {{date}} - Initial Creation

**Purpose**: {{initial_purpose}}
**Context**: {{context}}
**Implementation Notes**: {{implementation_notes}}
**Decisions**: {{decisions}}

## Change Log

*Changes will be documented here as the file evolves.*

### Feature Addition

**Date**: {{date}}
**Change**: Describe the new feature
**Rationale**: Why was this feature needed?
**Impact**: How does this affect existing functionality?

### Bug Fix

**Date**: {{date}}
**Issue**: Describe the bug that was fixed
**Solution**: How was the issue resolved?
**Prevention**: Steps taken to prevent recurrence

### Refactoring

**Date**: {{date}}
**Scope**: What was refactored?
**Goal**: What was the objective?
**Outcome**: What was achieved?

## Templates for Future Entries

Use these templates when documenting changes:

**Feature Addition**:
- Date: [YYYY-MM-DD]
- Change: [Brief description]
- Rationale: [Why needed]
- Impact: [Effect on system]

**Bug Fix**:
- Date: [YYYY-MM-DD]
- Issue: [Problem description]
- Solution: [How fixed]
- Prevention: [Future prevention]

**Refactoring**:
- Date: [YYYY-MM-DD]
- Scope: [What changed]
- Goal: [Objective]
- Outcome: [Result]

---
*History maintained by spec-cli*
"""


def get_default_template_config() -> TemplateConfig:
    """Get the default template configuration.

    Returns:
        TemplateConfig with default templates
    """
    return TemplateConfig(
        index=DEFAULT_INDEX_TEMPLATE, history=DEFAULT_HISTORY_TEMPLATE
    )


def get_minimal_template_config() -> TemplateConfig:
    """Get a minimal template configuration for quick documentation.

    Returns:
        TemplateConfig with minimal templates
    """
    minimal_index = """# {{filename}}

**Location**: {{filepath}}
**Purpose**: {{purpose}}

## Overview

{{overview}}

## Usage

```{{file_extension}}
{{example_usage}}
```

## Notes

{{notes}}
"""

    minimal_history = """# History for {{filename}}

**Location**: {{filepath}}

## {{date}} - Initial Creation

**Purpose**: {{purpose}}
**Context**: {{context}}
"""

    return TemplateConfig(index=minimal_index, history=minimal_history)


def get_comprehensive_template_config() -> TemplateConfig:
    """Get a comprehensive template configuration for detailed documentation.

    Returns:
        TemplateConfig with comprehensive templates
    """
    comprehensive_index = (
        DEFAULT_INDEX_TEMPLATE
        + """

## Architecture

{{architecture}}

## Design Patterns

{{design_patterns}}

## Code Quality

{{code_quality}}

## Monitoring

{{monitoring}}

## Troubleshooting

{{troubleshooting}}

## Migration Guide

{{migration_guide}}
"""
    )

    comprehensive_history = (
        DEFAULT_HISTORY_TEMPLATE
        + """

## Detailed Analysis

### Architecture Evolution
{{architecture_evolution}}

### Performance Impact
{{performance_impact}}

### Security Implications
{{security_implications}}

### Technical Debt
{{technical_debt}}

### Future Planning
{{future_planning}}
"""
    )

    return TemplateConfig(index=comprehensive_index, history=comprehensive_history)


# Template configurations registry
TEMPLATE_PRESETS = {
    "default": get_default_template_config,
    "minimal": get_minimal_template_config,
    "comprehensive": get_comprehensive_template_config,
}


def get_template_preset(preset_name: str) -> TemplateConfig:
    """Get a template configuration by preset name.

    Args:
        preset_name: Name of the preset ("default", "minimal", "comprehensive")

    Returns:
        TemplateConfig for the preset

    Raises:
        ValueError: If preset name is not recognized
    """
    if preset_name not in TEMPLATE_PRESETS:
        available = ", ".join(TEMPLATE_PRESETS.keys())
        raise ValueError(
            f"Unknown template preset '{preset_name}'. Available: {available}"
        )

    return TEMPLATE_PRESETS[preset_name]()
